repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Run Ruff Lint
        entry: uv run ruff check src tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: ruff-format-check
        name: Run Ruff Format Check
        entry: uv run ruff format --check src tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: pytest-check
        name: Run Pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
